version: '3'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:6082"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
