version: '3.6'
services:
    vosint-api:
        image: vienai/vosint-api:1.0.2
        environment:
            - ENVIRONMENT=PRODUCTION
            - mong_host=mongodb://admin:aivosint%400258@mong7.vosint.edu.vn:60007/admin?authSource=admin&authMechanism=SCRAM-SHA-256
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong7.vosint.edu.vn:60007/admin?authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - PIPELINE_API=http://vosint-pipeline-master:6101
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - SUMMARIZE_API=http://vosint-sumthesis-hpc08:1510/ext
            - KEYWORD_EXTRACTION_API=http://vosint-extraction-hpc08:1510/api/extraction
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
        ports:
            - 3688:6102
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
            placement:
                constraints:
                    - node.hostname==srv1

        volumes:
            - vosint_backend_static:/usr/app/static
        networks:
            - vosint3_system_network

volumes:
    vosint_backend_static:
        driver: local
        name: vosint_backend_static
        driver_opts:
            type: none
            o: bind
            device: "/home/vosint/deployment/static"

networks:
    vosint3_system_network:
        external: true
